# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 892b4dcce3dbf73aac56f5f4263bdcde7f15c7e9dd6a449bd0b1dfc7867fb41444c4b343860025bcbff01cf89602c56cc0d22554d507533f52f53dd3a6dfeb07

test:
  secret_key_base: f3481fe694edf03bb4d3a87da8edfe5690dbd830c4e33bf62e7babe1507829522f603fad04003f2c38488228b4db7d8292ac1283714bbca70c9a819fc8e976d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
